# _config.yml (configuration file)
title: "Sonal Katiyar's Resume"
email: "sonalka000@gmail.com"
description: "Resume of Sonal Katiyar, a professional with experience in business administration, banking, and analytics."
author: Sonal Katiyar
theme: minima
